package br.com.primeup.cadastro.dominio.enums;

public enum EnumCargoNivel {
	
	 DIRETOR, GERENTE, ESPECIALISTA_DE_TI, ARQUITETO_DE_TI,
	 	ANALISTA_DE_TI_SR, DESENVOLVEDOR_SR, ANALISTA_DE_TI_PL,
	 		DESENVOLVEDOR_PLENO, ANALISTA_DE_TI_JR, DESENVOLVEDOR_JR,
	 			TRAINEE_DE_TI_1, TRAINEE_DE_TI_2, TRAINEE_DE_TI_3,
	 			TRAINEE_DE_TI_4, TRAINEE_DE_TI_5, ESTAGIARIO;
	
}
